# Generated by Django 2.1.3 on 2019-03-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPersonalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='m', max_length=1)),
                ('numberidentification', models.CharField(max_length=11, unique=True)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('cellphone', models.CharField(blank=True, max_length=8, null=True)),
                ('phone', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.FileField(blank=True, default='static/image/perfil/teacher/perfildefault.png', null=True, upload_to='static/image/perfil/teacher/')),
                ('nacionality', models.CharField(default='cubana', max_length=50)),
                ('pasaport', models.CharField(blank=True, max_length=10, null=True)),
                ('degree', models.CharField(choices=[('Ing.', 'Ingeniero'), ('Lic.', 'Licenciado'), ('Ms.C.', 'Master en Ciencias'), ('Dr.C.', 'Doctor en Ciencias'), ('PhD.C.', 'Postdoctor en Ciencias')], default='Lic.', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teacherpersonalinformation',
            unique_together={('name', 'lastname', 'numberidentification')},
        ),
    ]
