# Generated by Django 2.1.3 on 2019-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0003_auto_20190314_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpersonalinformation',
            name='ocupation',
            field=models.CharField(choices=[('te', 'Trabajador Estatal'), ('ac', 'Ama/o de Casa'), ('tp', 'Trabajador Privado'), ('do', 'Desocupado'), ('es', 'Estudiante')], default='do', max_length=2),
        ),
    ]
