# Generated by Django 2.1.3 on 2019-05-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0004_auto_20190314_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=12)),
                ('openregistre', models.DateField(auto_now=True)),
                ('deadline', models.DateField(auto_now=True)),
            ],
        ),
    ]
