# Generated by Django 2.1.3 on 2019-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0005_courseinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='image',
            field=models.FileField(blank=True, default='static/image/perfil/course/perfildefault.png', null=True, upload_to='static/image/perfil/course/'),
        ),
    ]
