# Generated by Django 2.1.3 on 2019-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0006_courseinformation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinformation',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='openregistre',
            field=models.DateField(blank=True),
        ),
    ]
