# Generated by Django 2.1.3 on 2019-09-20 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0007_auto_20190523_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.BooleanField(default=False)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.CourseInformation')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.StudentPersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.CourseInformation')),
                ('teacherId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.TeacherPersonalInformation')),
            ],
        ),
        migrations.CreateModel(
            name='GroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.CourseInformation')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.StudentPersonalInformation')),
            ],
        ),
        migrations.AddField(
            model_name='assistence',
            name='clasroomId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.ClassRoom'),
        ),
        migrations.AddField(
            model_name='assistence',
            name='grouplistId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.GroupList'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinformation',
            unique_together={('name', 'courseId', 'teacherId')},
        ),
    ]
