# Generated by Django 2.1.3 on 2019-09-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0008_auto_20190920_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupinformation',
            name='edition',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='groupinformation',
            unique_together={('name', 'courseId', 'teacherId', 'edition')},
        ),
    ]
