# Generated by Django 2.1.3 on 2019-09-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0009_auto_20190920_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouplist',
            name='groupId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.GroupInformation'),
        ),
    ]
