# Generated by Django 2.1.3 on 2019-09-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0010_auto_20190920_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouplist',
            old_name='groupId',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='grouplist',
            old_name='studentId',
            new_name='student',
        ),
    ]
