# Generated by Django 2.1.3 on 2019-09-20 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0011_auto_20190920_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistence',
            old_name='clasroomId',
            new_name='clasroom',
        ),
        migrations.RenameField(
            model_name='assistence',
            old_name='grouplistId',
            new_name='grouplist',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='courseId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='studentId',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='groupinformation',
            old_name='courseId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='groupinformation',
            old_name='teacherId',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='grouplist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.Candidate'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinformation',
            unique_together={('name', 'course', 'teacher', 'edition')},
        ),
    ]
