# Generated by Django 2.1.3 on 2019-09-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0012_auto_20190920_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinformation',
            name='edition',
            field=models.CharField(default='2019-2020', max_length=9),
        ),
    ]
