# Generated by Django 2.1.3 on 2019-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0015_auto_20190925_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
