# Generated by Django 2.1.3 on 2019-09-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0016_courseinformation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinformation',
            name='yearMax',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AddField(
            model_name='courseinformation',
            name='yearMin',
            field=models.PositiveSmallIntegerField(default=18),
        ),
    ]
