# Generated by Django 2.1.3 on 2019-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0017_auto_20190927_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpersonalinformation',
            name='qrcode',
            field=models.FileField(blank=True, null=True, upload_to='static/image/perfil/student/qrcode'),
        ),
        migrations.AlterField(
            model_name='studentpersonalinformation',
            name='image',
            field=models.FileField(blank=True, default='static/image/perfil/student/perfildefault.png', null=True, upload_to='static/image/perfil/student/'),
        ),
    ]
