# Generated by Django 2.1.3 on 2019-11-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0018_auto_20191018_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
