# Generated by Django 2.1.3 on 2019-11-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0020_remove_candidate_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
