# Generated by Django 2.1.3 on 2019-11-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0022_groupinformation_current'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouplist',
            unique_together={('group', 'student')},
        ),
    ]
