# Generated by Django 2.1.3 on 2019-11-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0023_auto_20191122_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raspberrys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Docencia.ClassRoom')),
            ],
        ),
        migrations.RenameField(
            model_name='assistence',
            old_name='clasroom',
            new_name='classroom',
        ),
        migrations.AlterField(
            model_name='courseinformation',
            name='image',
            field=models.FileField(blank=True, default='static/image/perfil/course/perfildefault.png', null=True, upload_to='static/image/perfil/course'),
        ),
        migrations.AlterField(
            model_name='studentpersonalinformation',
            name='image',
            field=models.FileField(blank=True, default='static/image/perfil/student/perfildefault.png', null=True, upload_to='static/image/perfil/student'),
        ),
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='image',
            field=models.FileField(blank=True, default='static/image/perfil/teacher/perfildefault.png', null=True, upload_to='static/image/perfil/teacher'),
        ),
    ]
