# Generated by Django 2.1.3 on 2019-11-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0024_auto_20191128_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistence',
            name='date',
        ),
        migrations.AddField(
            model_name='assistence',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
