# Generated by Django 2.1.3 on 2019-11-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0025_auto_20191128_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistence',
            name='dateTime',
            field=models.CharField(max_length=100),
        ),
    ]
