# Generated by Django 2.1.3 on 2019-11-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0026_auto_20191128_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistence',
            name='dateTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
