# Generated by Django 2.1.3 on 2019-12-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0027_auto_20191128_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistence',
            name='classroom',
        ),
        migrations.AddField(
            model_name='groupinformation',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Docencia.ClassRoom'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinformation',
            unique_together={('name', 'course', 'teacher', 'edition', 'classroom')},
        ),
    ]
