# Generated by Django 2.1.3 on 2019-12-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0029_auto_20191202_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistence',
            name='status',
            field=models.CharField(choices=[('a', 'Asistencia'), ('i', 'Inasistencia'), ('t', 'Tardanza')], default='a', max_length=2),
        ),
    ]
