# Generated by Django 2.1.3 on 2019-12-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0032_auto_20191202_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistence',
            name='dateTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
