# Generated by Django 2.1.3 on 2019-12-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0033_auto_20191202_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistence',
            old_name='dateTime',
            new_name='assis_dateTime',
        ),
        migrations.RenameField(
            model_name='assistence',
            old_name='grouplist',
            new_name='assis_grouplist',
        ),
        migrations.RenameField(
            model_name='assistence',
            old_name='status',
            new_name='assis_status',
        ),
    ]
