# Generated by Django 2.1.3 on 2019-12-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0034_auto_20191209_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistence',
            name='assis_mode',
            field=models.CharField(choices=[('m', 'Manual'), ('a', 'Auto')], default='m', max_length=1),
        ),
    ]
