# Generated by Django 2.1.3 on 2019-12-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0035_assistence_assis_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpersonalinformation',
            name='qrcode',
        ),
    ]
