# Generated by Django 2.1.3 on 2019-12-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Docencia', '0036_remove_studentpersonalinformation_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherpersonalinformation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
