# Generated by Django 2.1.3 on 2019-12-17 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0037_teacherpersonalinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherpersonalinformation',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
