# Generated by Django 2.1.3 on 2020-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docencia', '0038_auto_20191217_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinformation',
            name='edition',
            field=models.CharField(default='2020-2021', max_length=9),
        ),
    ]
